[workspace]
members = [
    "apps/api",
    "base",
    "shared",
    "migration",
    "id_macro",
    "user/base",
    "user/api",
    "user/migration",
    "geo/base",
    "geo/api",
    "geo/migration",
    "train/base",
    "train/api",
    "train/migration",
    "hotel/base",
    "hotel/api",
    "hotel/migration",
    "dish/base",
    "dish/api",
    "dish/migration",
    "object_storage/base",
    "object_storage/api",
    "order/api",
    "order/base",
    "order/migration",
]
resolver = "2"
