//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::dish::Entity as Dish;
pub use super::route::Entity as Route;
pub use super::station::Entity as Station;
pub use super::takeaway_dish::Entity as TakeawayDish;
pub use super::takeaway_shop::Entity as TakeawayShop;
pub use super::train::Entity as Train;
