//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hotel_order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid: Uuid,
    pub hotel_id: i32,
    pub begin_date: Date,
    pub end_date: Date,
    pub hotel_room_type_id: i32,
    pub person_info_id: i32,
    pub pay_transaction_id: Option<i32>,
    pub refund_transaction_id: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price: Decimal,
    pub create_time: DateTimeWithTimeZone,
    pub active_time: DateTimeWithTimeZone,
    pub complete_time: DateTimeWithTimeZone,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hotel::Entity",
        from = "Column::HotelId",
        to = "super::hotel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hotel,
    #[sea_orm(
        belongs_to = "super::hotel_room_type::Entity",
        from = "Column::HotelRoomTypeId",
        to = "super::hotel_room_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    HotelRoomType,
    #[sea_orm(
        belongs_to = "super::person_info::Entity",
        from = "Column::PersonInfoId",
        to = "super::person_info::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PersonInfo,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::PayTransactionId",
        to = "super::transaction::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transaction2,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::RefundTransactionId",
        to = "super::transaction::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Transaction1,
}

impl Related<super::hotel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hotel.def()
    }
}

impl Related<super::hotel_room_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HotelRoomType.def()
    }
}

impl Related<super::person_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
