//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod prelude;

pub mod city;
pub mod dish;
pub mod dish_order;
pub mod hotel;
pub mod hotel_order;
pub mod hotel_rating;
pub mod hotel_room_type;
pub mod message;
pub mod occupied_room;
pub mod occupied_seat;
pub mod person_info;
pub mod route;
pub mod seat_type;
pub mod seat_type_in_train_type;
pub mod seat_type_mapping;
pub mod station;
pub mod takeaway_dish;
pub mod takeaway_order;
pub mod takeaway_shop;
pub mod train;
pub mod train_order;
pub mod train_schedule;
pub mod train_type;
pub mod transaction;
pub mod user;
