//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::city::Entity as City;
pub use super::dish::Entity as Dish;
pub use super::dish_order::Entity as DishOrder;
pub use super::hotel::Entity as Hotel;
pub use super::hotel_order::Entity as HotelOrder;
pub use super::hotel_rating::Entity as HotelRating;
pub use super::hotel_room_type::Entity as HotelRoomType;
pub use super::message::Entity as Message;
pub use super::occupied_room::Entity as OccupiedRoom;
pub use super::occupied_seat::Entity as OccupiedSeat;
pub use super::person_info::Entity as PersonInfo;
pub use super::route::Entity as Route;
pub use super::seat_type::Entity as SeatType;
pub use super::seat_type_in_train_type::Entity as SeatTypeInTrainType;
pub use super::seat_type_mapping::Entity as SeatTypeMapping;
pub use super::station::Entity as Station;
pub use super::takeaway_dish::Entity as TakeawayDish;
pub use super::takeaway_order::Entity as TakeawayOrder;
pub use super::takeaway_shop::Entity as TakeawayShop;
pub use super::train::Entity as Train;
pub use super::train_order::Entity as TrainOrder;
pub use super::train_route::Entity as TrainRoute;
pub use super::train_type::Entity as TrainType;
pub use super::transaction::Entity as Transaction;
pub use super::user::Entity as User;
