//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "route")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub line_id: i64,
    pub station_id: i32,
    pub arrival_time: i32,
    pub departure_time: i32,
    pub order: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::station::Entity",
        from = "Column::StationId",
        to = "super::station::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Station,
}

impl Related<super::station::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Station.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
