//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "seat_type_in_train_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub seat_type_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub train_type_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::seat_type::Entity",
        from = "Column::SeatTypeId",
        to = "super::seat_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SeatType,
    #[sea_orm(
        belongs_to = "super::train_type::Entity",
        from = "Column::TrainTypeId",
        to = "super::train_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TrainType,
}

impl Related<super::seat_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeatType.def()
    }
}

impl Related<super::train_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
