//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "takeaway_dish")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub dish_type: String,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price: Decimal,
    pub takeaway_shop_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::takeaway_order::Entity")]
    TakeawayOrder,
    #[sea_orm(
        belongs_to = "super::takeaway_shop::Entity",
        from = "Column::TakeawayShopId",
        to = "super::takeaway_shop::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TakeawayShop,
}

impl Related<super::takeaway_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TakeawayOrder.def()
    }
}

impl Related<super::takeaway_shop::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TakeawayShop.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
