//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "takeaway_shop")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub uuid: Uuid,
    pub name: String,
    pub station_id: i64,
    pub images: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::station::Entity",
        from = "Column::StationId",
        to = "super::station::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Station,
    #[sea_orm(has_many = "super::takeaway_dish::Entity")]
    TakeawayDish,
}

impl Related<super::station::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Station.def()
    }
}

impl Related<super::takeaway_dish::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TakeawayDish.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
