//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "train_schedule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub train_id: i32,
    pub departure_date: Date,
    pub line_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::occupied_seat::Entity")]
    OccupiedSeat,
    #[sea_orm(
        belongs_to = "super::train::Entity",
        from = "Column::TrainId",
        to = "super::train::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Train,
    #[sea_orm(has_many = "super::train_order::Entity")]
    TrainOrder,
}

impl Related<super::occupied_seat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OccupiedSeat.def()
    }
}

impl Related<super::train::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Train.def()
    }
}

impl Related<super::train_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrainOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
