//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "train_order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub train_id: i64,
    pub departure_date: Date,
    pub seat_type_id: i64,
    pub seat_id: i32,
    pub begin_station_id: i64,
    pub end_station_id: i64,
    pub person_info_id: i64,
    pub pay_transaction_id: i64,
    pub refund_transaction_id: i64,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub price: Decimal,
    pub create_time: DateTimeWithTimeZone,
    pub active_time: DateTimeWithTimeZone,
    pub complete_time: DateTimeWithTimeZone,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dish_order::Entity")]
    DishOrder,
    #[sea_orm(
        belongs_to = "super::person_info::Entity",
        from = "Column::PersonInfoId",
        to = "super::person_info::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PersonInfo,
    #[sea_orm(
        belongs_to = "super::seat_type::Entity",
        from = "Column::SeatTypeId",
        to = "super::seat_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SeatType,
    #[sea_orm(
        belongs_to = "super::station::Entity",
        from = "Column::BeginStationId",
        to = "super::station::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Station2,
    #[sea_orm(
        belongs_to = "super::station::Entity",
        from = "Column::EndStationId",
        to = "super::station::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Station1,
    #[sea_orm(has_many = "super::takeaway_order::Entity")]
    TakeawayOrder,
    #[sea_orm(
        belongs_to = "super::train::Entity",
        from = "Column::TrainId",
        to = "super::train::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Train,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::PayTransactionId",
        to = "super::transaction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transaction2,
    #[sea_orm(
        belongs_to = "super::transaction::Entity",
        from = "Column::RefundTransactionId",
        to = "super::transaction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transaction1,
}

impl Related<super::dish_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DishOrder.def()
    }
}

impl Related<super::person_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonInfo.def()
    }
}

impl Related<super::seat_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeatType.def()
    }
}

impl Related<super::takeaway_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TakeawayOrder.def()
    }
}

impl Related<super::train::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Train.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
