[package]
name = "order_api"
version = "0.1.0"
edition = "2024"

[dependencies]

order_base = { path = "../base" }
shared = { path = "../../shared" }
order_migration = { path = "../migration" }

sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }

actix-web = { version = "4.9", features = ["cookies"] }
serde = { version = "1.0", features = ["derive"] }

tracing-subscriber = "0.3"
tracing-actix-web = "0.7"
uuid = { version = "1.16.0", features = ["v4"] }

dotenvy = { version = "0.15" }

tokio = { version = "1", features = ["full"] }