//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::occupied_seat::Entity as OccupiedSeat;
pub use super::person_info::Entity as PersonInfo;
pub use super::route::Entity as Route;
pub use super::seat_availability::Entity as SeatAvailability;
pub use super::seat_type::Entity as SeatType;
pub use super::seat_type_in_train_type::Entity as SeatTypeInTrainType;
pub use super::seat_type_mapping::Entity as SeatTypeMapping;
pub use super::station::Entity as Station;
pub use super::train::Entity as Train;
pub use super::train_schedule::Entity as TrainSchedule;
pub use super::train_type::Entity as TrainType;
