//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod hotel;
pub mod hotel_rating;
pub mod hotel_room_type;

pub mod city;
pub mod occupied_room;
pub mod person_info;
pub mod station;
pub mod user;
