//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub mod dish;
pub mod dish_order;
pub mod hotel;
pub mod hotel_order;
pub mod hotel_room_type;
pub mod person_info;
pub mod prelude;
pub mod seat_type;
pub mod seat_type_mapping;
pub mod station;
pub mod takeaway_dish;
pub mod takeaway_order;
pub mod train;
pub mod train_order;
pub mod train_schedule;
pub mod transaction;
pub mod user;
