//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::dish::Entity as Dish;
pub use super::dish_order::Entity as DishOrder;
pub use super::hotel::Entity as Hotel;
pub use super::hotel_order::Entity as HotelOrder;
pub use super::hotel_room_type::Entity as HotelRoomType;
pub use super::person_info::Entity as PersonInfo;
pub use super::seat_type::Entity as SeatType;
pub use super::seat_type_mapping::Entity as SeatTypeMapping;
pub use super::station::Entity as Station;
pub use super::takeaway_dish::Entity as TakeawayDish;
pub use super::takeaway_order::Entity as TakeawayOrder;
pub use super::train::Entity as Train;
pub use super::train_order::Entity as TrainOrder;
pub use super::train_schedule::Entity as TrainSchedule;
pub use super::transaction::Entity as Transaction;
pub use super::user::Entity as User;
