[package]
name = "dish_api"
version = "0.1.0"
edition = "2024"

[dependencies]

dish_base = { path = "../base" }
shared = { path = "../../shared" }
migration = { path = "../../migration" }

sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }

actix-web = { version = "4.9", features = ["cookies"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-actix-web = "0.7"

dotenvy = { version = "0.15" }

tokio = { version = "1", features = ["full"] }