[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]

base = { path = "../../base" }
shared = { path = "../../shared" }

actix-web = { version = "4.9", features = ["cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"