[package]
name = "order_base"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../../shared" }
id_macro = { path = "../../id_macro" }

tokio = { version = "1", features = ["full"] }
sea-orm = { version = "1.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
thiserror = "2.0"
anyhow = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }

async-trait = "0.1"
rust_decimal = "1.37"

tracing = "0.1"

lapin = "2.5"

uuid = { version = "1.16", features = ["v4"] }
