apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: swiftjourney
resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - storage.yaml
  - db.yaml
  - redis.yaml
  - rabbitmq.yaml
  - minio.yaml
  - minio-init-job.yaml
  - user.yaml
  - geo.yaml
  - train.yaml
  - hotel.yaml
  - dish.yaml
  - order.yaml
  - object-storage.yaml
  - frontend.yaml
  - gateway-nginx.yaml
  - ingress.yaml
  - hpa.yaml
images:
  - name: saitewasreset/swiftjourney-user
    newTag: v0.1.0
  - name: saitewasreset/swiftjourney-geo
    newTag: v0.1.0
  - name: saitewasreset/swiftjourney-train
    newTag: v0.1.0
  - name: saitewasreset/swiftjourney-hotel
    newTag: v0.1.0
  - name: saitewasreset/swiftjourney-dish
    newTag: v0.1.0
  - name: saitewasreset/swiftjourney-order
    newTag: v0.1.0
  - name: saitewasreset/swiftjourney-object-storage
    newTag: v0.1.0
  - name: saitewasreset/swiftjourney-frontend
    newTag: v0.1.0
