apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: swiftjourney
stringData:
  POSTGRES_USER: swiftjourney
  POSTGRES_PASSWORD: swiftjourney
  POSTGRES_DB: swiftjourney
  RABBITMQ_USER: swiftjourney
  RABBITMQ_PASS: swiftjourney
  MINIO_ROOT_USER: swiftjourney
  MINIO_ROOT_PASSWORD: swiftjourney
  MINIO_ACCESS_KEY: ForSuperEarth!
  MINIO_SECRET_KEY: WorkersOfTheWorld,Unite!
