[package]
name = "object_storage_api"
version = "0.1.0"
edition = "2024"

[dependencies]

object_storage_base = { path = "../base" }
shared = { path = "../../shared" }

actix-web = { version = "4.9", features = ["cookies"] }

tracing = "0.1"
tracing-subscriber = "0.3"
tracing-actix-web = "0.7"
uuid = { version = "1.16.0", features = ["v4"] }

dotenvy = { version = "0.15" }


tokio = { version = "1", features = ["full"] }